# Generated by Django 4.1.7 on 2023-04-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='profile_pic',
            field=models.ImageField(blank=True, default='chatproject\\static\\images\\yrdpd.jpg', null=True, upload_to=''),
        ),
    ]
