# Generated by Django 4.1.7 on 2023-04-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_alter_profilemodel_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='profile_pic',
            field=models.ImageField(blank=True, default='gofg_7CJTSER.jpg', null=True, upload_to=''),
        ),
    ]
